name: weshier-deploy-workflow

on: workflow_dispatch

jobs:
  deploy-server:
    runs-on: ubuntu-latest
    steps:
      - name: ssh pipelines
        uses: cross-the-world/ssh-pipeline@master
        with:
          host: ${{ secrets.WESHIER_SERVER_HOST }}
          user: ${{ secrets.WESHIER_SERVER_USER }}
          pass: ${{ secrets.WESHIER_SERVER_PASS }}
          port: ${{ secrets.WESHIER_SERVER_PORT }}
          script: |
            pwd && ls
