name: weshier-go-workflow

on: workflow_dispatch

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [1.15.6]
    steps:
      # 设置服务器时区为东八区
      - name: Set time zone
        run: sudo timedatectl set-timezone 'Asia/Shanghai'

      - name: checkout repository
        uses: actions/checkout@v2

      - name: setup go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}

      - name: login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: build docker image and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_REPOSITORY }}/weshier:go

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      # - name: ssh pipelines
      #   uses: cross-the-world/ssh-pipeline@master
      #   with:
      #     host: ${{ secrets.WESHIER_SERVER_HOST }}
      #     user: ${{ secrets.WESHIER_SERVER_USER }}
      #     pass: ${{ secrets.WESHIER_SERVER_PASS }}
      #     port: ${{ secrets.WESHIER_SERVER_PORT }}
      #     script: |
      #       pwd
      #       docker login -u ${{ secrets.DOCKER_HUB_UNAME }} -p ${{ secrets.DOCKER_HUB_PASS }}
      #       docker pull ${{ secrets.DOCKER_HUB_REPOSITORY }}/weshier:go
      #       bash ${{ secrets.WESHIER_DEPLOY_PATH }}/run-go-docker.sh
